name: digital_arhat
description: "Digital Arhat - Pakistan ka apna digital mandi system"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8

  # 🔥 Firebase Core & Services
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2
  firebase_auth: ^6.1.4
  firebase_app_check: ^0.4.1+5
  firebase_remote_config: ^6.1.4
  firebase_storage: ^13.0.6
  firebase_messaging: ^16.1.1
  flutter_local_notifications: 20.1.0

  fl_chart: 1.1.1

  # 🏗️ State Management
  provider: ^6.1.5+1

  # 📸 Multimedia & Audio
  image_picker: ^1.2.1
  flutter_image_compress: 2.4.0
  camera: ^0.12.0
  video_player: ^2.8.1
  video_compress: 3.1.4
  record: 6.2.0
  audioplayers: 6.5.1
  path_provider: ^2.1.5
  image: ^4.8.0
  timezone: ^0.10.0
  local_auth: ^2.3.0
  crypto: ^3.0.6
  flutter_secure_storage: ^9.2.4

  # 🌐 HTTP & API
  http: ^1.6.0
  html: ^0.15.5

  # ✅ Form validation
  form_field_validator: 1.1.0

  # ✨ Premium UI/UX & Animations
  google_fonts: 8.0.2
  flutter_animate: ^4.5.2
  geolocator: 14.0.2
  mask_text_input_formatter: 2.9.0
  intl_phone_field: ^3.2.0
  url_launcher: ^6.3.2
  weather_animation: 1.2.0
  weather: ^3.2.1
  iconsax: 0.0.8
  lottie: ^3.3.2
  flutter_svg: ^2.2.3
  marquee: 2.3.0
  cached_network_image: 3.4.1
  shared_preferences: ^2.5.3
  intl: 0.20.2
  package_info_plus: 9.0.0
  app_links: 7.0.0
  speech_to_text: ^7.2.0

  # 🤖 Google AI & ML Kit
  google_generative_ai: ^0.4.7
  google_mlkit_face_detection: 0.13.2
  google_mlkit_text_recognition: 0.15.1
  google_mlkit_commons: 0.11.1

  # 🏁 QR & Delivery Verification
  qr_flutter: 4.1.0
  mobile_scanner: 7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/categories/
    - assets/bakra_mandi/
    - assets/images/
    - assets/images/logo.png
    - assets/images/circuit_pattern.png
    - assets/images/no_stock.svg
    - assets/lottie/sun.json
    - assets/lottie/rain.json
    - assets/lottie/cloudy.json
    - assets/data/pakistan_locations.json

  fonts:
    - family: JameelNoori
      fonts:
        - asset: assets/fonts/jameel_noori_nastaleeq.ttf
    - family: Jameel Noori
      fonts:
        - asset: assets/fonts/jameel_noori_nastaleeq.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logo.png
  adaptive_icon_foreground: assets/logo.png
  adaptive_icon_background: "#002810"
  remove_alpha_ios: true