// Script to populate name_ur fields in pakistan_locations.json
// Run: node tool/add_urdu_names.js

const fs = require('fs');
const path = require('path');

const jsonPath = path.join(__dirname, '..', 'assets', 'data', 'pakistan_locations.json');

// Comprehensive English->Urdu map for Pakistan locations
const URDU = {
  // Provinces
  'Azad Kashmir': 'آزاد کشمیر',
  'Balochistan': 'بلوچستان',
  'Gilgit Baltistan': 'گلگت بلتستان',
  'Islamabad': 'اسلام آباد',
  'Khyber Pakhtunkhwa': 'خیبر پختونخوا',
  'Punjab': 'پنجاب',
  'Sindh': 'سندھ',

  // Punjab Districts
  'Attock': 'اٹک',
  'Bahawalnagar': 'بہاولنگر',
  'Bahawalpur': 'بہاولپور',
  'Bhakkar': 'بھکر',
  'Chakwal': 'چکوال',
  'Chiniot': 'چنیوٹ',
  'Dera Ghazi Khan': 'ڈیرہ غازی خان',
  'Faisalabad': 'فیصل آباد',
  'Gujranwala': 'گوجرانوالہ',
  'Gujrat': 'گجرات',
  'Hafizabad': 'حافظ آباد',
  'Jhang': 'جھنگ',
  'Jhelum': 'جہلم',
  'Kasur': 'قصور',
  'Khanewal': 'خانیوال',
  'Khushab': 'خوشاب',
  'Lahore': 'لاہور',
  'Leiah': 'لیہ',
  'Lodhran': 'لودھراں',
  'Mandi Bahauddin': 'منڈی بہاؤالدین',
  'Mianwali': 'میانوالی',
  'Multan': 'ملتان',
  'Muzaffargarh': 'مظفرگڑھ',
  'Nankana Sahib': 'ننکانہ صاحب',
  'Narowal': 'نارووال',
  'Okara': 'اوکاڑہ',
  'Pakpattan': 'پاکپتن',
  'Rahim Yar Khan': 'رحیم یار خان',
  'Rajanpur': 'راجن پور',
  'Rawalpindi': 'راولپنڈی',
  'Sahiwal': 'ساہیوال',
  'Sargodha': 'سرگودھا',
  'Sheikhupura': 'شیخوپورہ',
  'Sialkot': 'سیالکوٹ',
  'Toba Tek Singh': 'ٹوبہ ٹیک سنگھ',
  'Vehari': 'وہاڑی',

  // Punjab Tehsils
  'Attock City': 'اٹک شہر',
  'Hazro': 'حضرو',
  'Pindi Gheb': 'پنڈی گھیب',
  'Fateh Jang': 'فتح جنگ',
  'Bahawalnagar City': 'بہاولنگر شہر',
  'Chishtian': 'چشتیاں',
  'Hasilpur': 'حاصلپور',
  'Minchinabad': 'منچن آباد',
  'Bahawalpur City': 'بہاولپور شہر',
  'Ahmadpur East': 'احمد پور مشرقی',
  'Yazman': 'یزمان',
  'Bhakkar City': 'بھکر شہر',
  'Kallur Kot': 'کالور کوٹ',
  'Mankera': 'منکیرہ',
  'Chakwal City': 'چکوال شہر',
  'Talagang': 'تلہ گنگ',
  'Chiniot City': 'چنیوٹ شہر',
  'Bhawana': 'بھوانہ',
  'DG Khan': 'ڈی جی خان',
  'Taunsa': 'ٹونسہ',
  'Faisalabad City': 'فیصل آباد شہر',
  'Jaranwala': 'جڑانوالہ',
  'Samundri': 'سمندری',
  'Tandlianwala': 'ٹانڈلیانوالہ',
  'Gujranwala City': 'گوجرانوالہ شہر',
  'Kamoke': 'کاموکے',
  'Nowshera Virkan': 'نوشہرہ ورکاں',
  'Gujrat City': 'گجرات شہر',
  'Kharian': 'کھاریاں',
  'Hafizabad City': 'حافظ آباد شہر',
  'Pindi Bhattian': 'پنڈی بھٹیاں',
  'Jhang City': 'جھنگ شہر',
  'Shorkot': 'شورکوٹ',
  'Ahmadpur Sial': 'احمد پور سیال',
  'Jhelum City': 'جہلم شہر',
  'Sohawa': 'سوہاوہ',
  'Pattoki': 'پتوکی',
  'Chunian': 'چونیاں',
  'Kot Radha Kishan': 'کوٹ رادھا کشن',
  'Khanewal City': 'خانیوال شہر',
  'Mian Channu': 'میاں چنوں',
  'Kabirwala': 'کبیروالہ',
  'Khushab City': 'خوشاب شہر',
  'Noorpur Thal': 'نورپور تھل',
  'Quaidabad': 'قائد آباد',
  'Lahore City': 'لاہور شہر',
  'Ravi': 'راوی',
  'Shalimar': 'شالیمار',
  'Model Town': 'ماڈل ٹاؤن',
  'Cantt': 'چھاؤنی',
  'Leiah City': 'لیہ شہر',
  'Karor Lal Esan': 'کروڑ لعل عیسن',
  'Lodhran City': 'لودھراں شہر',
  'Kehror Pakka': 'کہرور پکا',
  'Mandi Bahauddin City': 'منڈی بہاؤالدین شہر',
  'Phalia': 'پھالیہ',
  'Mianwali City': 'میانوالی شہر',
  'Piplan': 'پی پلاں',
  'Esa Khel': 'عیسی خیل',
  'Multan City': 'ملتان شہر',
  'Shujabad': 'شجاع آباد',
  'Jalalpur Pirwala': 'جلال پور پیروالہ',
  'Muzaffargarh City': 'مظفرگڑھ شہر',
  'Kot Addu': 'کوٹ ادو',
  'Ali Pur': 'علی پور',
  'Nankana Sahib City': 'ننکانہ صاحب شہر',
  'Sangla Hill': 'سانگلہ ہل',
  'Narowal City': 'نارووال شہر',
  'Shakargarh': 'شکرگڑھ',
  'Okara City': 'اوکاڑہ شہر',
  'Depalpur': 'دیپالپور',
  'Renala Khurd': 'رینالہ خورد',
  'Pakpattan City': 'پاکپتن شہر',
  'Arifwala': 'عارف والا',
  'Rahim Yar Khan City': 'رحیم یار خان شہر',
  'Liaquatpur': 'لیاقت پور',
  'Sadiqabad': 'صادق آباد',
  'Rajanpur City': 'راجن پور شہر',
  'Jampur': 'جام پور',
  'Rawalpindi City': 'راولپنڈی شہر',
  'Kahuta': 'کہوٹہ',
  'Taxila': 'ٹیکسلا',
  'Gujar Khan': 'گجر خان',
  'Sahiwal City': 'ساہیوال شہر',
  'Chichawatni': 'چیچہ وطنی',
  'Sargodha City': 'سرگودھا شہر',
  'Bhalwal': 'بھلوال',
  'Sillanwali': 'سلانوالی',
  'Sheikhupura City': 'شیخوپورہ شہر',
  'Safdarabad': 'صفدرآباد',
  'Ferozewala': 'فیروزوالہ',
  'Sialkot City': 'سیالکوٹ شہر',
  'Daska': 'ڈسکہ',
  'Sambrial': 'سمبڑیال',
  'Pasrur': 'پسرور',
  'Toba Tek Singh City': 'ٹوبہ ٹیک سنگھ شہر',
  'Gojra': 'گوجرہ',
  'Kamalia': 'کمالیہ',
  'Vehari City': 'وہاڑی شہر',
  'Burewala': 'بوریوالہ',
  'Mailsi': 'میلسی',

  // Sindh Districts
  'Karachi': 'کراچی',
  'Karachi East': 'کراچی مشرق',
  'Karachi South': 'کراچی جنوب',
  'Karachi Central': 'کراچی وسط',
  'Karachi West': 'کراچی مغرب',
  'Karachi Malir': 'کراچی ملیر',
  'Hyderabad': 'حیدرآباد',
  'Sukkur': 'سکھر',
  'Larkana': 'لاڑکانہ',
  'Nawabshah': 'نوابشاہ',
  'Shaheed Benazirabad': 'شہید بینظیر آباد',
  'Mirpur Khas': 'میرپور خاص',
  'Sanghar': 'سانگھڑ',
  'Tando Allahyar': 'ٹنڈو اللہ یار',
  'Tando Muhammad Khan': 'ٹنڈو محمد خان',
  'Badin': 'بدین',
  'Thatta': 'ٹھٹھہ',
  'Jamshoro': 'جامشورو',
  'Dadu': 'دادو',
  'Naushahro Feroze': 'نوشہروفیروز',
  'Khairpur': 'خیرپور',
  'Shikarpur': 'شکارپور',
  'Jacobabad': 'جیکب آباد',
  'Kashmore': 'کشمور',
  'Kamber Shahdadkot': 'کامبر شہداد کوٹ',
  'Matiari': 'ماٹیاری',
  'Umerkot': 'عمر کوٹ',
  'Ghotki': 'گھوٹکی',
  'Qambar Shahdadkot': 'قمبر شہداد کوٹ',
  'Sujawal': 'سجاول',

  // Sindh Tehsils
  'Saddar': 'صدر',
  'Latifabad': 'لطیف آباد',
  'Qasimabad': 'قاسم آباد',
  'Hyderabad City': 'حیدرآباد شہر',
  'Sukkur City': 'سکھر شہر',
  'Rohri': 'روہڑی',
  'Pano Aqil': 'پانو عقیل',
  'Larkana City': 'لاڑکانہ شہر',
  'Dokri': 'ڈوکری',
  'Ratodero': 'رتو ڈیرو',
  'Nawabshah City': 'نوابشاہ شہر',
  'Sakrand': 'سکرنڈ',
  'Mirpur Khas City': 'میرپور خاص شہر',
  'Kot Ghulam Muhammad': 'کوٹ غلام محمد',
  'Digri': 'ڈگری',
  'Badin City': 'بدین شہر',
  'Talhar': 'تلہار',
  'Matli': 'مٹلی',
  'Thatta City': 'ٹھٹھہ شہر',
  'Gharo': 'گھارو',
  'Dadu City': 'دادو شہر',
  'Khairpur City': 'خیرپور شہر',
  'Kingri': 'کنگری',
  'Jacobabad City': 'جیکب آباد شہر',
  'Garhi Khairo': 'گڑھی خیرو',
  'Ghotki City': 'گھوٹکی شہر',
  'Ubauro': 'عبیدو',

  // KPK Districts
  'Peshawar': 'پشاور',
  'Mardan': 'مردان',
  'Swat': 'سوات',
  'Dir Lower': 'ضلع دیر زیریں',
  'Dir Upper': 'ضلع دیر بالائی',
  'Charsadda': 'چارسدہ',
  'Nowshera': 'نوشہرہ',
  'Kohat': 'کوہاٹ',
  'Buner': 'بونیر',
  'Mansehra': 'مانسہرہ',
  'Abbottabad': 'ایبٹ آباد',
  'Haripur': 'ہری پور',
  'Swabi': 'صوابی',
  'Bannu': 'بنوں',
  'Dera Ismail Khan': 'ڈیرہ اسماعیل خان',
  'Tank': 'ٹانک',
  'Lakki Marwat': 'لکی مروت',
  'Karak': 'کرک',
  'Hangu': 'ہنگو',
  'Shangla': 'شانگلہ',
  'Battagram': 'بٹگرام',
  'Kohistan': 'کوہستان',
  'Tor Ghar': 'تورغر',
  'Malakand': 'مالاکنڈ',
  'Chitral': 'چترال',
  'Chitral Upper': 'بالائی چترال',
  'Chitral Lower': 'زیریں چترال',
  'Kurram': 'کرم',
  'Orakzai': 'اورکزئی',
  'Mohmand': 'مہمند',
  'Bajaur': 'باجوڑ',
  'South Waziristan': 'جنوبی وزیرستان',
  'North Waziristan': 'شمالی وزیرستان',
  'Khyber': 'خیبر',

  // KPK Tehsils
  'Peshawar City': 'پشاور شہر',
  'Badaber': 'بداب',
  'Chamkani': 'چمکنی',
  'Mardan City': 'مردان شہر',
  'Takht Bhai': 'تخت بھائی',
  'Katlang': 'کٹلانگ',
  'Mingora': 'منگورہ',
  'Saidu Sharif': 'سیدو شریف',
  'Kabal': 'کبل',
  'Khawazakhela': 'خوازہ خیلہ',
  'Charsadda City': 'چارسدہ شہر',
  'Shabqadar': 'شبقدر',
  'Nowshera City': 'نوشہرہ شہر',
  'Jehangira': 'جہانگیرہ',
  'Pabbi': 'پابی',
  'Kohat City': 'کوہاٹ شہر',
  'Lachi': 'لاچی',
  'Mansehra City': 'مانسہرہ شہر',
  'Balakot': 'بالاکوٹ',
  'Oghi': 'اوگی',
  'Abbottabad City': 'ایبٹ آباد شہر',
  'Havelian': 'ہویلیاں',
  'Haripur City': 'ہری پور شہر',
  'Swabi City': 'صوابی شہر',
  'Razar': 'رزار',
  'Bannu City': 'بنوں شہر',
  'Domel': 'ڈومیل',
  'DI Khan City': 'ڈی آئی خان شہر',
  'Paroa': 'پروا',
  'Tank City': 'ٹانک شہر',
  'Lakki City': 'لکی شہر',
  'Karak City': 'کرک شہر',

  // Balochistan Districts
  'Quetta': 'کوئٹہ',
  'Zhob': 'ژوب',
  'Turbat': 'تربت',
  'Khuzdar': 'خضدار',
  'Sibi': 'سبی',
  'Mastung': 'ماسٹنگ',
  'Chaman': 'چمن',
  'Hub': 'حب',
  'Nushki': 'نوشکی',
  'Panjgur': 'پنجگور',
  'Gwadar': 'گوادر',
  'Makran': 'مکران',
  'Awaran': 'آواران',
  'Kech': 'کیچ',
  'Kalat': 'قلات',
  'Kharan': 'خاران',
  'Bolan': 'بولان',
  'Jhal Magsi': 'جھل مگسی',
  'Lasbela': 'لسبیلہ',
  'Loralai': 'لورالائی',
  'Musakhel': 'موسیٰ خیل',
  'Pishin': 'پشین',
  'Qila Abdullah': 'قلعہ عبداللہ',
  'Qila Saifullah': 'قلعہ سیف اللہ',
  'Sherani': 'شیرانی',
  'Washuk': 'واشک',
  'Ziarat': 'زیارت',
  'Harnai': 'ہرنائی',
  'Kohlu': 'کوہلو',
  'Dera Bugti': 'ڈیرہ بگٹی',
  'Nasirabad': 'نصیرآباد',
  'Kachhi': 'کچھی',
  'Sohbatpur': 'صحبت پور',
  'Jaffarabad': 'جعفرآباد',
  'Lehri': 'لہری',
  'Usta Muhammad': 'اوستہ محمد',

  // Balochistan Tehsils
  'Quetta City': 'کوئٹہ شہر',
  'Sariab': 'ساریاب',
  'Chiltan': 'چلتن',
  'Pishin City': 'پشین شہر',
  'Killa Abdullah': 'قلعہ عبداللہ',
  'Zhob City': 'ژوب شہر',
  'Loralai City': 'لورالائی شہر',
  'Turbat City': 'تربت شہر',
  'Khuzdar City': 'خضدار شہر',
  'Kharan City': 'خاران شہر',
  'Gwadar City': 'گوادر شہر',
  'Sibi City': 'سبی شہر',
  'Chaman City': 'چمن شہر',
  'Hub City': 'حب شہر',

  // Islamabad
  'Islamabad City': 'اسلام آباد شہر',
  'Rural Islamabad': 'دیہی اسلام آباد',

  // Gilgit Baltistan Districts
  'Gilgit': 'گلگت',
  'Skardu': 'سکردو',
  'Hunza': 'ہنزہ',
  'Nagar': 'نگر',
  'Ghizer': 'غذر',
  'Astore': 'اسٹور',
  'Diamer': 'دیامر',
  'Ghanche': 'غانچھے',
  'Shigar': 'شگر',
  'Kharmang': 'خرمنگ',
  'Roundu': 'راؤنڈو',
  'Baltistan': 'بلتستان',

  // GB Tehsils
  'Gilgit City': 'گلگت شہر',
  'Skardu City': 'سکردو شہر',
  'Chilas': 'چلاس',
  'Darel': 'دارال',
  'Tangir': 'تنگیر',
  'Gupis': 'گوپس',
  'Yasin': 'یاسین',
  'Ishkoman': 'اشکومن',

  // Azad Kashmir Districts
  'Bagh': 'باغ',
  'Bhimber': 'بھمبر',
  'Jhelum Valley': 'جہلم ویلی',
  'Haveli': 'ہویلی',
  'Kotli': 'کوٹلی',
  'Mirpur': 'میرپور',
  'Muzaffarabad': 'مظفرآباد',
  'Neelum': 'نیلم',
  'Poonch': 'پونچھ',
  'Sudhnati': 'سدھنوتی',
  'Hattian': 'ہٹیاں',

  // AJK Tehsils
  'Bagh City': 'باغ شہر',
  'Dhir Kot': 'ڈھیرکوٹ',
  'Harighel': 'ہاریگھیل',
  'Barnala': 'برنالہ',
  'Bhimber City': 'بھمبر شہر',
  'Samahni': 'سماہنی',
  'Chikar': 'چیکار',
  'Hattian Bala': 'ہٹیاں بالا',
  'Leepa': 'لیپا',
  'Haveli City': 'ہویلی شہر',
  'Khurshid Abad': 'خورشید آباد',
  'Mumtazabad': 'ممتاز آباد',
  'Kotli City': 'کوٹلی شہر',
  'Charhoi': 'چڑہوئی',
  'Mirpur City': 'میرپور شہر',
  'Dudyal': 'دودیال',
  'Muzaffarabad City': 'مظفرآباد شہر',
  'Neelum City': 'نیلم شہر',
  'Poonch City': 'پونچھ شہر',
  'Sudhnati City': 'سدھنوتی شہر',
  // Additional AJK tehsils
  'Dulliya Jattan': 'دلیا جٹاں',
  'Fatehpur Thakiala': 'فتح پور ٹھکیالہ',
  'Khui Ratta': 'کھوئی رتہ',
  'Sehnsa': 'سہنسہ',
  'Dadyal': 'ڈڈیال',
  'Naseerabad': 'نصیرآباد',
  'Athmuqam': 'اٹھ مقام',
  'Sharda': 'شاردہ',
  'Abbaspur': 'عباس پور',
  'Hajira': 'ہاجرہ',
  'Rawalakot': 'راولاکوٹ',
  'Thorar': 'تھوڑار',
  'Sudhnoti': 'سدھنوتی',
  'Baluch': 'بلوچ',
  'Mong': 'مونگ',
  'Pallandari': 'پلندری',
  'Tarar Khal': 'تارڑ خال',

  // Balochistan extra tehsils
  'Jhal Jhao': 'جھل جھاؤ',
  'Mashkai': 'مشکئی',
  'Gishekore': 'گیشکور',
  'Barkhan': 'بارکھان',
  'Rakhni': 'رخنی',
  'Dalbandin': 'دالبندین',
  'Nokkundi': 'نوک کنڈی',
  'Taftan': 'تفتان',
  'Chagai': 'چاغی',
  'Phelawagh': 'پھیلاواگ',
  'Sui': 'سوئی',
  'Jiwani': 'جیوانی',
  'Ormara': 'اورماڑہ',
  'Pasni': 'پسنی',
  'Sunster': 'سنسٹر',
  'Shahrigh': 'شاہریغ',
  'Gandakha': 'گندیکھہ',
  'Jhat Pat': 'جھت پٹ',
  'Usta Mohammad': 'اوستہ محمد',
  'Gandawa': 'گنداوہ',
  'Dhadar': 'دھادر',
  'Mach': 'ماچھ',
  'Sanni': 'سنی',
  'Balanari': 'بلہ ناری',
  'Khattan': 'کھتن',
  'Khaliqabad': 'خالق آباد',
  'Buleda': 'بلیدہ',
  'Turbat City': 'تربت شہر',
  'Mand': 'منڈ',
  'Hoshab': 'ہوشاب',
  'Dasht': 'دشت',
  'Panjgur City': 'پنجگور شہر',
  'Panjur': 'پنجور',
  'Gwadar City': 'گوادر شہر',
  'Nushki City': 'نوشکی شہر',
  'Mastung City': 'ماسٹنگ شہر',
  'Kalat City': 'قلات شہر',
  'Surab': 'سوراب',
  'Mangochar': 'مانگوچر',
  'Awaran City': 'آواران شہر',
  'Khuzdar City': 'خضدار شہر',
  'Zehri': 'ظہری',
  'Wadh': 'ودھ',
  'Sibi City': 'سبی شہر',
  'Lehri': 'لہری',
  'Jaffarabad': 'جعفرآباد',
  'Kachhi': 'کچھی',
  'Sohbatpur': 'صحبت پور',
  'Usta Muhammad': 'اوستہ محمد',
  'Kohlu City': 'کوہلو شہر',
  'Maiwand': 'میوند',
  'Harnai City': 'ہرنائی شہر',
  'Ziarat City': 'زیارت شہر',
  'Zhob City': 'ژوب شہر',
  'Sherani City': 'شیرانی شہر',
  'Musakhel City': 'موسیٰ خیل شہر',
  'Wad': 'واد',
  'Washuk City': 'واشک شہر',
  'Lasbela City': 'لسبیلہ شہر',
  'Hub City': 'حب شہر',
  'Uthal': 'اوتھل',
  'Bela': 'بیلہ',
  'Windi': 'ونڈی',

  // Sindh additional tehsils
  'Sakrand': 'سکرنڈ',
  'Qambar': 'قمبر',
  'Shahdadkot': 'شہداد کوٹ',
  'Kandhkot': 'کندھ کوٹ',
  'Kashmore City': 'کشمور شہر',
  'Mirpur Mathelo': 'میرپور ماتھیلو',
  'Obaro': 'اوباڑو',
  'Ghotki City': 'گھوٹکی شہر',
  'Daharki': 'ڈہرکی',
  'Ubauro': 'عبیدو',
  'Kandiaro': 'کنڈیارو',
  'Moro': 'موڑو',
  'Mehrabpur': 'مہرابپور',

  // KPK additional
  'Barikot': 'باری کوٹ',
  'Matta': 'متہ',
  'Bahrain': 'بحرین',
  'Charbagh': 'چارباغ',
  'Khwazakhela': 'خوازہ خیلہ',
  'Timergara': 'تیمرگرہ',
  'Adenzai': 'اڈینزئی',
  'Samarbagh': 'سمر باغ',
  'Munda': 'منڈہ',
  'Lal Qila': 'لال قلعہ',
  'Balambat': 'بلمبٹ',
  'Wari': 'واری',
  'Kalkot': 'کال کوٹ',
  'Doaba': 'دوآبہ',
  'Khanpur': 'خانپور',
  'Thall': 'تھل',
  'Darra Adam Khel': 'دارہ آدم خیل',
  'Bara': 'بارہ',
  'Jamrud': 'جمرود',
  'Landi Kotal': 'لنڈی کوتل',

  // Gilgit Baltistan additional
  'Gilgit City': 'گلگت شہر',
  'Skardu City': 'سکردو شہر',
  'Chilas': 'چلاس',
  'Darel': 'دارال',
  'Tangir': 'تنگیر',
  'Gupis': 'گوپس',
  'Yasin': 'یاسین',
  'Ishkoman': 'اشکومن',
  'Punial': 'پنیال',
  'Bagrot': 'بگروٹ',
  'Kargah': 'کرگاہ',
  'Juglot': 'جگلوٹ',
  'Aliabad': 'علی آباد',
  'Gojal': 'گوجال',
  'Nagar City': 'نگر شہر',
  'Astore City': 'اسٹور شہر',
  'Bunji': 'بونجی',
  'Ghanche City': 'غانچھے شہر',
  'Khaplu': 'خپلو',
  'Shigar City': 'شگر شہر',
  'Kharmang City': 'خرمنگ شہر',
  'Ghizer City': 'غذر شہر',

  // Punjab extra cities
  'Phool Nagar': 'پھول نگر',
  'Habibabad': 'حبیب آباد',
  'Kasur City': 'قصور شہر',
  'Khudian Khas': 'کھڈیاں خاص',
  'Halla': 'ہلہ',
  'Allahabad': 'الہ آباد',
  'Mustafabad': 'مصطفی آباد',
  'Shahdara': 'شاہدرہ',
  'Data Ganj Bakhsh': 'داتا گنج بخش',
  'Mughalpura': 'مغل پورہ',
  'Harbanspura': 'ہربنس پورہ',
  'Kot Lakhpat': 'کوٹ لکھپت',
  'DHA': 'ڈی ایچ اے',
  'Lahore Cantt': 'لاہور چھاؤنی',
  'Raja Bazar': 'راجہ بازار',
  'Wah Cantt': 'واہ چھاؤنی',
  'Madina Town': 'مدینہ ٹاؤن',
  'Lyallpur Town': 'لائلپور ٹاؤن',
  'Shah Rukn-e-Alam': 'شاہ رکنِ عالم',
  'Cantt Multan': 'ملتان چھاؤنی',
  'Satellite Town': 'سیٹلائٹ ٹاؤن',
  'Sialkot Cantt': 'سیالکوٹ چھاؤنی',
  'Allama Iqbal Chowk': 'علامہ اقبال چوک',
  'F-10': 'ایف دس',
  'G-11': 'جی گیارہ',
  'I-8': 'آئی آٹھ',
  'Gulshan-e-Iqbal': 'گلشنِ اقبال',
  'Johar': 'جوہر',
  'Hirabad': 'ہیرآباد',
  'Market Tower': 'مارکیٹ ٹاور',
  'University Town': 'یونیورسٹی ٹاؤن',
  'Hayatabad': 'حیات آباد',
  'Par Hoti': 'پار ہوتی',
  'Jinnah Town': 'جناح ٹاؤن',
  'Satellite Town Quetta': 'سیٹلائٹ ٹاؤن کوئٹہ',
  // Additional missing districts
  'Killa Saifullah': 'قلعہ سیف اللہ',
  'Shaheed Sikandarabad': 'شہید سکندرآباد',
  'Duki': 'دوکی',
  'Diamir': 'دیامر',
  'Gupis-Yasin': 'گوپس - یاسین',
  'Rondu': 'روندو',
  'Batagram': 'بٹگرام',
  'D. I. Khan': 'ڈیرہ اسماعیل خان',
  'Kohistan Lower': 'کوہستان زیریں',
  'Kohistan Upper': 'کوہستان بالائی',
  'Kolai Palas Kohistan': 'کولائی پالاس کوہستان',
  'Lower Dir': 'ضلع دیر زیریں',
  'Upper Dir': 'ضلع دیر بالائی',
  'Central Karachi': 'کراچی وسط',
  'East Karachi': 'کراچی مشرق',
  'Kambar Shahdad Kot': 'کامبر شہداد کوٹ',
  'Korangi Karachi': 'کوہستان کراچی',
  'Malir Karachi': 'ملیر کراچی',
  'Shaheed Benazir Abad': 'شہید بینظیر آباد',
  'South Karachi': 'کراچی جنوب',
  'Tharparkar': 'تھرپارکر',
  'Umer Kot': 'عمر کوٹ',
  'West Karachi': 'کراچی مغرب',
};

// Strip UTF-8 BOM if present before parsing
let rawContent = fs.readFileSync(jsonPath, 'utf8');
if (rawContent.charCodeAt(0) === 0xFEFF) {
  rawContent = rawContent.slice(1);
}
const data = JSON.parse(rawContent);

let updated = 0;
let missing = [];

function applyUrdu(item, level) {
  const en = (item.name_en || '').trim();
  if (!en) return;
  if (!item.name_ur || item.name_ur.trim() === '') {
    const ur = URDU[en];
    if (ur) {
      item.name_ur = ur;
      updated++;
    } else {
      missing.push({ level, name: en });
    }
  }
}

for (const province of (data.provinces || [])) {
  applyUrdu(province, 'province');
  for (const district of (province.districts || [])) {
    applyUrdu(district, 'district');
    for (const tehsil of (district.tehsils || [])) {
      applyUrdu(tehsil, 'tehsil');
      for (const city of (tehsil.cities || [])) {
        applyUrdu(city, 'city');
      }
    }
  }
}

fs.writeFileSync(jsonPath, JSON.stringify(data, null, 4), 'utf8');
console.log(`Updated ${updated} name_ur fields`);
if (missing.length > 0) {
  console.log(`\nMissing Urdu for ${missing.length} items:`);
  missing.forEach(m => console.log(`  [${m.level}] ${m.name}`));
}
