# Fix missing Urdu translations for Pakistan location tehsils
$urduMap = @{
    # Balochistan
    "Kech (Turbat)"            = "کیچ (تربت)"
    "Tump"                     = "تمپ"
    "Sar Kharan"               = "سر خاران"
    "Tomulk"                   = "تومولک"
    "Mola"                     = "مولا"
    "Naal"                     = "نال"
    "Dobandi"                  = "ڈوبانڈی"
    "Gulistan"                 = "گلستان"
    "Muslim Bagh"              = "مسلم باغ"
    "Kahan"                    = "کاہان"
    "Mawand"                   = "ماوند"
    "Dureji"                   = "ڈریجی"
    "Gaddani"                  = "گڈانی"
    "Kanraj"                   = "کنراج"
    "Sonmiani"                 = "سونمیانی"
    "Lakhra"                   = "لکھرا"
    "Lairi"                    = "لیری"
    "Bhag"                     = "بھاگ"
    "Mekhtar"                  = "مختار"
    "Dasht Spenzend"           = "دشت سپنزند"
    "Kirdgap"                  = "کردگیپ"
    "Drug"                     = "ڈرگ"
    "Chattar"                  = "چتر"
    "Dera Murad Jamali"        = "ڈیرہ مراد جمالی"
    "Tamboo"                   = "تمبو"
    "Gowargo"                  = "گوارگو"
    "Jaheen Parome"            = "جہین پارومی"
    "Gichk"                    = "گیچک"
    "Barshore"                 = "برشور"
    "Huramzai"                 = "حرامزئی"
    "Karezat"                  = "کاریزات"
    "Saranan"                  = "سرانان"
    "Panjpai"                  = "پنج پائی"
    "Quetta Saddar"            = "کوئٹہ سدر"
    "Mashkhel"                 = "مشکیل"
    "Basima"                   = "باسیمہ"
    "Nag"                      = "ناگ"
    "Shaogari"                 = "شاوگری"
    "Kakar Khurasan"           = "کاکر خراسان"
    "Sinjawi"                  = "سنجاوی"
    # Gilgit Baltistan
    "Shounter"                 = "شونتر"
    "Daghoni"                  = "داغونی"
    "Mashabbrum"               = "ماشابرم"
    "Ali Abad"                 = "علی آباد"
    "Gamba"                    = "گمبا"
    "Sikandar Abad"            = "سکندر آباد"
    "Gultari"                  = "گلتری"
    "Phandar"                  = "پھندر"
    # KPK
    "Lora"                     = "لورا"
    "Lower Tanawal"            = "لوئر تناول"
    "Bar Chamarkand"           = "بار چمرکند"
    "Barang"                   = "بارانگ"
    "Khar"                     = "خار"
    "Mamund"                   = "مامند"
    "Nawagai"                  = "نواگئی"
    "Salarzai"                 = "سالارزئی"
    "Utman Khel"               = "عثمان خیل"
    "Baka Khel"                = "باکا خیل"
    "Kakki"                    = "کاکی"
    "Miryan"                   = "میریاں"
    "Wazir"                    = "وزیر"
    "Allai"                    = "الائی"
    "Daggar"                   = "ڈگر"
    "Gagra"                    = "گگڑہ"
    "Khado Khel"               = "خادو خیل"
    "Mandanr"                  = "منڈانڑ"
    "Tangi"                    = "تنگی"
    "Drosh"                    = "دروش"
    "Lotkoh"                   = "لوٹکوہ"
    "Mastuj"                   = "مستوج"
    "Mulkhow"                  = "مولکھو"
    "Daraban"                  = "درابن"
    "Kulachi"                  = "کلاچی"
    "Paharpur"                 = "پہاڑپور"
    "Darazinda"                = "دارازندہ"
    "Tall"                     = "ٹال"
    "Ghazi"                    = "غازی"
    "Banda Daud Shah"          = "بنڈہ داؤد شاہ"
    "Takht-E-Nasrati"          = "تخت نصرتی"
    "Mulagori"                 = "مولاگوری"
    "Gumbat"                   = "گمبٹ"
    "Pattan"                   = "پتان"
    "Bankad"                   = "بانکاد"
    "Dassu"                    = "داسو"
    "Kandia"                   = "کندیا"
    "Harban Basha"             = "ہربن باشا"
    "Seo"                      = "سیو"
    "Palas"                    = "پالاس"
    "Battera Kolai"            = "بٹیرہ کولائی"
    "Central Kurram"           = "وسطی کرم"
    "Lower Kurram"             = "زیریں کرم"
    "Upper Kurram"             = "بالائی کرم"
    "Sarai Naurang"            = "سرائے نورنگ"
    "Bettani"                  = "بیٹانی"
    "Lalqila"                  = "لال قلعہ"
    "Bat Khela"                = "بٹ خیلہ"
    "Dargai"                   = "درگئی"
    "Bala Kot"                 = "بالاکوٹ"
    "Baffa Pakhal"             = "بافہ پاکھل"
    "Darband"                  = "درونڈ"
    "Rustam"                   = "رستم"
    "Garhi Kapura"             = "گڑھی کپورہ"
    "Ambar"                    = "امبر"
    "Baizai"                   = "بائیزئی"
    "Halimzai"                 = "حالمزئی"
    "Khwazai"                  = "خوازئی"
    "Pandiali"                 = "پنڈیالی"
    "Prang Ghar"               = "پرانگ گھر"
    "Safi"                     = "صافی"
    "Yaka Ghund"               = "یکہ غند"
    "Data Khel"                = "ڈاٹہ خیل"
    "Dossali"                  = "دوسالی"
    "Garyum"                   = "گریوم"
    "Ghulam Khan"              = "غلام خان"
    "Mir Ali"                  = "میر علی"
    "Miran Shah"               = "میران شاہ"
    "Razmak"                   = "رزمک"
    "Shewa"                    = "شیوا"
    "Spinwam"                  = "سپین وام"
    "Shawal"                   = "شاوال"
    "Central Orakzai"          = "وسطی اورکزئی"
    "Ismailzai"                = "اسمعیل زئی"
    "Lower Orakzai"            = "زیریں اورکزئی"
    "Upper Orakzai"            = "بالائی اورکزئی"
    "Town-I"                   = "قصبہ اول"
    "Town-Ii"                  = "قصبہ دوم"
    "Town-Iii"                 = "قصبہ سوم"
    "Town-Iv"                  = "قصبہ چہارم"
    "Hassan Khel"              = "حسن خیل"
    "Alpuri"                   = "الپوری"
    "Bisham"                   = "بشام"
    "Chakisar"                 = "چکیسر"
    "Makhuzai"                 = "مخوزئی"
    "Martoong"                 = "مرتونگ"
    "Puran"                    = "پوران"
    "Birmal"                   = "بیرمل"
    "Ladha"                    = "لدھا"
    "Makin"                    = "ماکین"
    "Sararogha"                = "سراروغہ"
    "Serwakai"                 = "سروکئی"
    "Tiarza"                   = "تیارزہ"
    "Toi Khulla"               = "تائی خلہ"
    "Wana"                     = "وانا"
    "Lahor"                    = "لہور"
    "Topi"                     = "ٹوپی"
    "Babuzai"                  = "بابوزئی"
    "Kalam"                    = "کالام"
    "Khwaza Khela"             = "خوازہ خیلہ"
    "Matta Kharirai"           = "متہ خریرئی"
    "Matta Sebujni"            = "متہ سیبوجنی"
    "Jandola"                  = "جنڈولہ"
    "Judba"                    = "جڈبہ"
    "Khander"                  = "خانڈر"
    "Barawal"                  = "براول"
    "Dir"                      = "دیر"
    "Khall"                    = "خال"
    "Shrengal"                 = "شرینگل"
    "Larjam"                   = "لارجام"
    # Punjab
    "Hasan Abdal"              = "حسن ابدال"
    "Jand"                     = "جنڈ"
    "Fort Abbas"               = "فورٹ عباس"
    "Haroonabad"               = "ہارونآباد"
    "Khairpur Tamewali"        = "خیرپور تامیوالی"
    "Darya Khan"               = "دریا خان"
    "Kalur Kot"                = "کالور کوٹ"
    "Choa Saidan Shah"         = "چوآ سیدن شاہ"
    "Kallar Kahar"             = "کلر کہار"
    "Tala Gang"                = "تلہ گنگ"
    "Lalian"                   = "لالیاں"
    "D.G Khan (Tribal Area)"   = "ڈی جی خان (قبائلی علاقہ)"
    "Kot Chatta"               = "کوٹ چٹہ"
    "Chak Jhumra"              = "چک جھمرہ"
    "Faisalabad Sadar"         = "فیصل آباد سدر"
    "Summundri"                = "سمندری"
    "Tandlian Wala"            = "ٹنڈلیانوالہ"
    "Wazirabad"                = "وزیرآباد"
    "Sarai Alamgir"            = "سرائے عالمگیر"
    "Athara Hazari"            = "اٹھارہ ہزاری"
    "Dina"                     = "ڈینہ"
    "Pind Dadan Khan"          = "پنڈ دادن خان"
    "Jahanian"                 = "جہانیاں"
    "Naushera"                 = "نوشیرہ"
    "Noorpur"                  = "نورپور"
    "Choubara"                 = "چوبارہ"
    "Dunyapur"                 = "دنیاپور"
    "Kahror Pacca"             = "کہرور پکا"
    "Malakwal"                 = "ملکوال"
    "Isakhel"                  = "عیسیٰ خیل"
    "Multan Saddar"            = "ملتان سدر"
    "Alipur"                   = "علی پور"
    "Jatoi"                    = "جتوئی"
    "Shah Kot"                 = "شاہ کوٹ"
    "Zafarwal"                 = "ظفروال"
    "Arif Wala"                = "عارفوالہ"
    "Liaqatpur"                = "لیاقت پور"
    "Rajanpur (Tribal Area)"   = "راجن پور (قبائلی علاقہ)"
    "Rojhan"                   = "روجھان"
    "Kallar Sayaddan"          = "کلر سیداں"
    "Kotli Sattian"            = "کوٹلی ستیاں"
    "Murree"                   = "مری"
    "Kot Momin"                = "کوٹ مومن"
    "Shahpur"                  = "شاہ پور"
    "Bhera"                    = "بھیرہ"
    "Muridke"                  = "مریدکے"
    "Sharak Pur"               = "شرق پور"
    "Pir Mahal"                = "پیر محل"
    # Sindh
    "Shaheed Fazil Rahu"       = "شہید فاضل راہو"
    "Tando Bago"               = "ٹنڈو باگو"
    "Gulberg Town"             = "گلبرگ ٹاؤن"
    "Liaqatabad Town"          = "لیاقت آباد ٹاؤن"
    "New Karachi Town"         = "نیو کراچی ٹاؤن"
    "North Nazimabad Town"     = "نارتھ ناظم آباد ٹاؤن"
    "Johi"                     = "جوہی"
    "Khairpur Nathan Shah"     = "خیرپور ناتھن شاہ"
    "Mehar"                    = "مہر"
    "Gulshan Iqbal Town"       = "گلشن اقبال ٹاؤن"
    "Jamshaid Town"            = "جمشید ٹاؤن"
    "Khangarh"                 = "خانگڑھ"
    "Thul"                     = "ٹھُل"
    "Kotri"                    = "کوٹری"
    "Manjhand"                 = "منجھند"
    "Sehwan Sharif"            = "سیہون شریف"
    "Thano Bula Khan"          = "ٹھانو بولا خان"
    "Meero Khan"               = "میرو خان"
    "Nasir Abad"               = "ناصر آباد"
    "Qambar Ali Khan"          = "قمبر علی خان"
    "Qubo Saeed Khan"          = "قبو سعید خان"
    "Shahdad Kot"              = "شہداد کوٹ"
    "Sijawal Junejo"           = "سجاول جونیجو"
    "Warah"                    = "وارہ"
    "Kandh Kot"                = "کنڈھ کوٹ"
    "Tangwani"                 = "تنگوانی"
    "Faiz Ganj"                = "فیض گنج"
    "Gambat"                   = "گمبٹ"
    "Kot Diji"                 = "کوٹ ڈیجی"
    "Nara"                     = "نارا"
    "Sobho Dero"               = "صبھو ڈیرو"
    "Thari Meer Wah"           = "تھاری میر واہ"
    "Korangi Town"             = "کورنگی ٹاؤن"
    "Landhi Town"              = "لانڈھی ٹاؤن"
    "Shah Faisal Town"         = "شاہ فیصل ٹاؤن"
    "Baqrani"                  = "باقرانی"
    "Rato Dero"                = "راتو ڈیرو"
    "Bin Qasim Town"           = "بن قاسم ٹاؤن"
    "Gadap Town"               = "گڈاپ ٹاؤن"
    "Malir Town"               = "ملیر ٹاؤن"
    "Hala"                     = "ہالہ"
    "Saeedabad"                = "سعیدآباد"
    "Hussain Bux Muree"        = "حسین بخش مری"
    "Jhudo"                    = "جھوڈو"
    "Shuja Abad"               = "شجاع آباد"
    "Sindhri"                  = "سندھڑی"
    "Bhiria"                   = "بھریا"
    "Mehrab Pur"               = "محراب پور"
    "Jam Nawaz Ali"            = "جام نواز علی"
    "Khipro"                   = "کھپرو"
    "Shahdadpur"               = "شہداد پور"
    "Sinjhoro"                 = "سنجھورو"
    "Tando Adam"               = "ٹنڈو آدم"
    "Daulat Pur"               = "دولت پور"
    "Daur"                     = "داور"
    "Garhi Yasin"              = "گڑھی یاسین"
    "Lakhi"                    = "لاکھی"
    "Kemari Town"              = "کیماڑی ٹاؤن"
    "Liyari Town"              = "لیاری ٹاؤن"
    "Saddar Town"              = "صدر ٹاؤن"
    "Jati"                     = "جاتی"
    "Kharo Chan"               = "کھارو چھان"
    "Mirpur Bathoro"           = "میرپور باٹھورو"
    "Shah Bunder"              = "شاہ بندر"
    "New Sukkur"               = "نیو سکھر"
    "Salehpat"                 = "صالح پت"
    "Chamber"                  = "چیمبر"
    "Jhando Mari"              = "جھانڈو ماری"
    "Bulri Shah Karim"         = "بلڑی شاہ کریم"
    "Tando Ghulam Hyder"       = "ٹنڈو غلام حیدر"
    "Chachro"                  = "چاچڑو"
    "Dahli"                    = "ڈاہلی"
    "Diplo"                    = "ڈپلو"
    "Islam Kot"                = "اسلام کوٹ"
    "Mithi"                    = "مٹھی"
    "Nagar Parkar"             = "ننگر پارکر"
    "Kaloi"                    = "قلوئی"
    "Ghorabari"                = "گھورا باڑی"
    "Keti Bunder"              = "کیٹی بندر"
    "Mirpur Sakro"             = "میرپور ساکرو"
    "Kunri"                    = "کنری"
    "Pithoro"                  = "پیتھورو"
    "Samaro"                   = "سامارو"
    "Baldia Town"              = "بلدیہ ٹاؤن"
    "Orangi Town"              = "اورنگی ٹاؤن"
    "Site Town"                = "سائٹ ٹاؤن"
}

$jsonPath = "f:\Appdevelopment_new\digital_arhat\assets\data\pakistan_locations.json"
$rawJson = [System.IO.File]::ReadAllText($jsonPath, [System.Text.Encoding]::UTF8)
$json = $rawJson | ConvertFrom-Json

$fixedCount = 0
foreach ($province in $json.provinces) {
    foreach ($district in $province.districts) {
        foreach ($tehsil in $district.tehsils) {
            $nameEn = $tehsil.name_en
            $nameUr = $tehsil.name_ur
            if ([string]::IsNullOrWhiteSpace($nameUr) -and $urduMap.ContainsKey($nameEn)) {
                $tehsil.name_ur = $urduMap[$nameEn]
                $fixedCount++
            }
        }
    }
}

Write-Host "Fixed $fixedCount tehsil Urdu translations"

# Save with UTF-8 BOM-less encoding
$jsonOut = $json | ConvertTo-Json -Depth 10 -Compress:$false
[System.IO.File]::WriteAllText($jsonPath, $jsonOut, (New-Object System.Text.UTF8Encoding $false))
Write-Host "Saved to $jsonPath"

# Verify - count remaining missing
$stillMissing = 0
$json2 = [System.IO.File]::ReadAllText($jsonPath, [System.Text.Encoding]::UTF8) | ConvertFrom-Json
foreach ($province in $json2.provinces) {
    foreach ($district in $province.districts) {
        foreach ($tehsil in $district.tehsils) {
            if ([string]::IsNullOrWhiteSpace($tehsil.name_ur)) {
                $stillMissing++
                Write-Host "STILL MISSING: $($province.name_en) > $($district.name_en) > $($tehsil.name_en)"
            }
        }
    }
}
Write-Host "Still missing after fix: $stillMissing"
