const Map<String, List<String>> pakistanDistrictsByProvince =
    <String, List<String>>{
      'Punjab': <String>[
        'Attock',
        'Bahawalnagar',
        'Bahawalpur',
        'Bhakkar',
        'Chakwal',
        'Chiniot',
        'Dera Ghazi Khan',
        'Faisalabad',
        'Gujranwala',
        'Gujrat',
        'Hafizabad',
        'Jhang',
        'Jhelum',
        'Kasur',
        'Khanewal',
        'Khushab',
        'Lahore',
        'Layyah',
        'Lodhran',
        'Mandi Bahauddin',
        'Mianwali',
        'Multan',
        'Muzaffargarh',
        'Narowal',
        'Nankana Sahib',
        'Okara',
        'Pakpattan',
        'Rahim Yar Khan',
        'Rajanpur',
        'Rawalpindi',
        'Sahiwal',
        'Sargodha',
        'Sheikhupura',
        'Sialkot',
        'Toba Tek Singh',
        'Vehari',
        'Murree',
        'Talagang',
        'Wazirabad',
      ],
      'Sindh': <String>[
        'Badin',
        'Dadu',
        'Ghotki',
        'Hyderabad',
        'Jacobabad',
        'Jamshoro',
        'Karachi Central',
        'Karachi East',
        'Karachi Keamari',
        'Karachi Korangi',
        'Karachi Malir',
        'Karachi South',
        'Karachi West',
        'Kashmore',
        'Khairpur',
        'Larkana',
        'Matiari',
        'Mirpurkhas',
        'Naushahro Feroze',
        'Qambar Shahdadkot',
        'Sanghar',
        'Shaheed Benazirabad',
        'Shikarpur',
        'Sujawal',
        'Sukkur',
        'Tando Allahyar',
        'Tando Muhammad Khan',
        'Thatta',
        'Tharparkar',
        'Umerkot',
      ],
      'KPK': <String>[
        'Abbottabad',
        'Bajaur',
        'Bannu',
        'Battagram',
        'Buner',
        'Charsadda',
        'Chitral Lower',
        'Chitral Upper',
        'Dera Ismail Khan',
        'Hangu',
        'Haripur',
        'Karak',
        'Khyber',
        'Kohat',
        'Kohistan Lower',
        'Kohistan Upper',
        'Kolai-Palas',
        'Kurram',
        'Lakki Marwat',
        'Lower Dir',
        'Lower South Waziristan',
        'Malakand',
        'Mansehra',
        'Mardan',
        'Mohmand',
        'North Waziristan',
        'Nowshera',
        'Orakzai',
        'Peshawar',
        'Shangla',
        'Swabi',
        'Swat',
        'Tank',
        'Torghar',
        'Upper Dir',
        'Upper South Waziristan',
      ],
      'Balochistan': <String>[
        'Awaran',
        'Barkhan',
        'Chagai',
        'Dera Bugti',
        'Gwadar',
        'Harnai',
        'Jafarabad',
        'Jhal Magsi',
        'Kachhi',
        'Kalat',
        'Kech',
        'Kharan',
        'Khuzdar',
        'Kohlu',
        'Lasbela',
        'Lehri',
        'Loralai',
        'Mastung',
        'Musakhel',
        'Nasirabad',
        'Nushki',
        'Panjgur',
        'Pishin',
        'Qila Abdullah',
        'Qila Saifullah',
        'Quetta',
        'Sherani',
        'Sibi',
        'Sohbatpur',
        'Washuk',
        'Zhob',
        'Ziarat',
      ],
      'Gilgit-Baltistan': <String>[
        'Astore',
        'Diamer',
        'Ghanche',
        'Ghizer',
        'Gilgit',
        'Hunza',
        'Kharmang',
        'Nagar',
        'Shigar',
        'Skardu',
      ],
      'Azad Kashmir': <String>[
        'Bagh',
        'Bhimber',
        'Hattian Bala',
        'Haveli',
        'Kotli',
        'Mirpur',
        'Muzaffarabad',
        'Neelum',
        'Poonch',
        'Sudhnoti',
      ],
      'Islamabad': <String>[
        'Islamabad',
      ],
    };

List<String> get allDistrictsSorted {
  final Set<String> unique = <String>{};
  for (final List<String> districts in pakistanDistrictsByProvince.values) {
    unique.addAll(districts);
  }
  final List<String> sorted = unique.toList()..sort();
  return sorted;
}
